--- config	2026-05-11 10:22:25.284504482 -0700
+++ config.orig	2026-05-11 10:17:50.359288446 -0700
@@ -42,7 +42,7 @@
 CONFIG_INIT_ENV_ARG_LIMIT=32
 # CONFIG_COMPILE_TEST is not set
 # CONFIG_WERROR is not set
-CONFIG_LOCALVERSION="lyric"
+CONFIG_LOCALVERSION=""
 CONFIG_LOCALVERSION_AUTO=y
 CONFIG_BUILD_SALT=""
 CONFIG_HAVE_KERNEL_GZIP=y
@@ -60,7 +60,7 @@
 # CONFIG_KERNEL_LZ4 is not set
 CONFIG_KERNEL_ZSTD=y
 CONFIG_DEFAULT_INIT=""
-CONFIG_DEFAULT_HOSTNAME="lyriclaptop"
+CONFIG_DEFAULT_HOSTNAME="archlinux"
 CONFIG_SYSVIPC=y
 CONFIG_SYSVIPC_SYSCTL=y
 CONFIG_SYSVIPC_COMPAT=y
@@ -443,7 +443,7 @@
 CONFIG_BHYVE_GUEST=y
 CONFIG_INTEL_TDX_GUEST=y
 CONFIG_CC_HAS_MARCH_NATIVE=y
-CONFIG_X86_NATIVE_CPU=y
+# CONFIG_X86_NATIVE_CPU is not set
 CONFIG_X86_INTERNODE_CACHE_SHIFT=6
 CONFIG_X86_L1_CACHE_SHIFT=6
 CONFIG_X86_TSC=y
@@ -575,7 +575,7 @@
 CONFIG_MODIFY_LDT_SYSCALL=y
 # CONFIG_STRICT_SIGALTSTACK_SIZE is not set
 CONFIG_HAVE_LIVEPATCH=y
-CONFIG_LIVEPATCH=y
+# CONFIG_LIVEPATCH is not set
 CONFIG_HAVE_KLP_BUILD=y
 CONFIG_X86_BUS_LOCK_DETECT=y
 # end of Processor type and features
@@ -7505,10 +7505,7 @@
 CONFIG_FRAMEBUFFER_CONSOLE_DEFERRED_TAKEOVER=y
 # end of Console display driver support
 
-CONFIG_LOGO=y
-# CONFIG_LOGO_LINUX_MONO is not set
-# CONFIG_LOGO_LINUX_VGA16 is not set
-CONFIG_LOGO_LINUX_CLUT224=y
+# CONFIG_LOGO is not set
 CONFIG_TRACE_GPU_MEM=y
 # end of Graphics support
 
