--- .config.old	2026-05-14 09:08:39.642176739 -0700
+++ .config	2026-05-14 09:56:50.330966016 -0700
@@ -4846,6 +4846,7 @@
 CONFIG_SERIAL_UARTLITE_NR_UARTS=1
 CONFIG_SERIAL_CORE=y
 CONFIG_SERIAL_CORE_CONSOLE=y
+CONFIG_CONSOLE_POLL=y
 CONFIG_SERIAL_JSM=m
 # CONFIG_SERIAL_LANTIQ is not set
 CONFIG_SERIAL_SCCNXP=m
@@ -6587,6 +6588,7 @@
 CONFIG_DVB_BUDGET=m
 CONFIG_DVB_BUDGET_CI=m
 CONFIG_DVB_BUDGET_AV=m
+# CONFIG_VIDEO_PCI_SKELETON is not set
 CONFIG_VIDEO_IPU3_CIO2=m
 CONFIG_VIDEO_INTEL_IPU6=m
 CONFIG_INTEL_VSC=m
@@ -7240,6 +7242,7 @@
 CONFIG_DRM_AMD_DC=y
 CONFIG_DRM_AMD_DC_FP=y
 CONFIG_DRM_AMD_DC_SI=y
+# CONFIG_DEBUG_KERNEL_DC is not set
 CONFIG_DRM_AMD_SECURE_DISPLAY=y
 # end of Display Engine Configuration
 
@@ -12266,7 +12269,7 @@
 # end of printk and dmesg options
 
 CONFIG_DEBUG_KERNEL=y
-# CONFIG_DEBUG_MISC is not set
+CONFIG_DEBUG_MISC=y
 
 #
 # Compile-time checks and compiler options
@@ -12309,9 +12312,29 @@
 CONFIG_DEBUG_FS_ALLOW_ALL=y
 # CONFIG_DEBUG_FS_ALLOW_NONE is not set
 CONFIG_HAVE_ARCH_KGDB=y
-# CONFIG_KGDB is not set
+CONFIG_KGDB=y
+CONFIG_KGDB_HONOUR_BLOCKLIST=y
+CONFIG_KGDB_SERIAL_CONSOLE=y
+CONFIG_KGDB_TESTS=y
+# CONFIG_KGDB_TESTS_ON_BOOT is not set
+CONFIG_KGDB_LOW_LEVEL_TRAP=y
+CONFIG_KGDB_KDB=y
+CONFIG_KDB_DEFAULT_ENABLE=0x1
+# CONFIG_KDB_KEYBOARD is not set
+CONFIG_KDB_CONTINUE_CATASTROPHIC=0
+CONFIG_ARCH_HAS_EARLY_DEBUG=y
 CONFIG_ARCH_HAS_UBSAN=y
-# CONFIG_UBSAN is not set
+CONFIG_UBSAN=y
+# CONFIG_UBSAN_TRAP is not set
+CONFIG_CC_HAS_UBSAN_BOUNDS_STRICT=y
+CONFIG_UBSAN_BOUNDS=y
+CONFIG_UBSAN_BOUNDS_STRICT=y
+CONFIG_UBSAN_SHIFT=y
+CONFIG_UBSAN_DIV_ZERO=y
+CONFIG_UBSAN_BOOL=y
+CONFIG_UBSAN_ENUM=y
+CONFIG_UBSAN_ALIGNMENT=y
+# CONFIG_TEST_UBSAN is not set
 CONFIG_HAVE_ARCH_KCSAN=y
 CONFIG_HAVE_KCSAN_COMPILER=y
 # CONFIG_KCSAN is not set
@@ -12399,7 +12422,7 @@
 CONFIG_BOOTPARAM_HUNG_TASK_PANIC=0
 CONFIG_DETECT_HUNG_TASK_BLOCKER=y
 # CONFIG_WQ_WATCHDOG is not set
-# CONFIG_WQ_CPU_INTENSIVE_REPORT is not set
+CONFIG_WQ_CPU_INTENSIVE_REPORT=y
 # CONFIG_TEST_LOCKUP is not set
 # end of Debug Oops, Lockups and Hangs
 
@@ -12411,7 +12434,8 @@
 # end of Scheduler Debugging
 
 # CONFIG_DEBUG_PREEMPT is not set
-# CONFIG_DEBUG_ATOMIC is not set
+CONFIG_DEBUG_ATOMIC=y
+# CONFIG_DEBUG_ATOMIC_LARGEST_ALIGN is not set
 
 #
 # Lock Debugging (spinlocks, mutexes, etc...)
@@ -12441,7 +12465,7 @@
 #
 # Debug kernel data structures
 #
-# CONFIG_DEBUG_LIST is not set
+CONFIG_DEBUG_LIST=y
 # CONFIG_DEBUG_PLIST is not set
 # CONFIG_DEBUG_SG is not set
 # CONFIG_DEBUG_NOTIFIERS is not set
@@ -12466,7 +12490,7 @@
 
 # CONFIG_DEBUG_WQ_FORCE_RR_CPU is not set
 # CONFIG_CPU_HOTPLUG_STATE_CONTROL is not set
-# CONFIG_LATENCYTOP is not set
+CONFIG_LATENCYTOP=y
 # CONFIG_DEBUG_CGROUP_REF is not set
 CONFIG_USER_STACKTRACE_SUPPORT=y
 CONFIG_NOP_TRACER=y
@@ -12552,7 +12576,7 @@
 # CONFIG_FTRACE_RECORD_RECURSION is not set
 # CONFIG_FTRACE_VALIDATE_RCU_IS_WATCHING is not set
 # CONFIG_FTRACE_STARTUP_TEST is not set
-# CONFIG_FTRACE_SORT_STARTUP_TEST is not set
+CONFIG_FTRACE_SORT_STARTUP_TEST=y
 # CONFIG_RING_BUFFER_STARTUP_TEST is not set
 # CONFIG_RING_BUFFER_VALIDATE_TIME_DELTAS is not set
 # CONFIG_MMIOTRACE_TEST is not set
@@ -12560,9 +12584,66 @@
 # CONFIG_SYNTH_EVENT_GEN_TEST is not set
 # CONFIG_KPROBE_EVENT_GEN_TEST is not set
 # CONFIG_HIST_TRIGGERS_DEBUG is not set
-# CONFIG_RV is not set
+CONFIG_RV=y
+CONFIG_RV_PER_TASK_MONITORS=2
+# CONFIG_RV_MON_WWNR is not set
+# CONFIG_RV_MON_RTAPP is not set
+CONFIG_RV_REACTORS=y
+CONFIG_RV_REACT_PRINTK=y
+CONFIG_RV_REACT_PANIC=y
 # CONFIG_PROVIDE_OHCI1394_DMA_INIT is not set
-# CONFIG_SAMPLES is not set
+CONFIG_SAMPLES=y
+CONFIG_SAMPLE_AUXDISPLAY=y
+CONFIG_SAMPLE_TRACE_EVENTS=m
+CONFIG_SAMPLE_TRACE_CUSTOM_EVENTS=m
+CONFIG_SAMPLE_TRACE_PRINTK=m
+CONFIG_SAMPLE_FTRACE_DIRECT=m
+CONFIG_SAMPLE_FTRACE_DIRECT_MULTI=m
+CONFIG_SAMPLE_FTRACE_OPS=m
+CONFIG_SAMPLE_TRACE_ARRAY=m
+CONFIG_SAMPLE_KOBJECT=m
+CONFIG_SAMPLE_KPROBES=m
+CONFIG_SAMPLE_KRETPROBES=m
+CONFIG_SAMPLE_HW_BREAKPOINT=m
+CONFIG_SAMPLE_FPROBE=m
+CONFIG_SAMPLE_KFIFO=m
+CONFIG_SAMPLE_KDB=m
+CONFIG_SAMPLE_RPMSG_CLIENT=m
+CONFIG_SAMPLE_LIVEPATCH=m
+CONFIG_SAMPLE_CONFIGFS=m
+CONFIG_SAMPLE_TSM_MR=m
+CONFIG_SAMPLE_VFIO_MDEV_MTTY=m
+CONFIG_SAMPLE_VFIO_MDEV_MDPY=m
+CONFIG_SAMPLE_VFIO_MDEV_MDPY_FB=m
+CONFIG_SAMPLE_VFIO_MDEV_MBOCHS=m
+CONFIG_SAMPLE_WATCHDOG=y
+# CONFIG_SAMPLE_HUNG_TASK is not set
+CONFIG_SAMPLES_RUST=y
+# CONFIG_SAMPLE_RUST_CONFIGFS is not set
+# CONFIG_SAMPLE_RUST_MINIMAL is not set
+# CONFIG_SAMPLE_RUST_MISC_DEVICE is not set
+# CONFIG_SAMPLE_RUST_PRINT is not set
+# CONFIG_SAMPLE_RUST_DMA is not set
+# CONFIG_SAMPLE_RUST_DEBUGFS is not set
+# CONFIG_SAMPLE_RUST_DEBUGFS_SCOPED is not set
+# CONFIG_SAMPLE_RUST_DRIVER_I2C is not set
+# CONFIG_SAMPLE_RUST_I2C_CLIENT is not set
+# CONFIG_SAMPLE_RUST_DRIVER_PCI is not set
+# CONFIG_SAMPLE_RUST_DRIVER_PLATFORM is not set
+# CONFIG_SAMPLE_RUST_DRIVER_USB is not set
+# CONFIG_SAMPLE_RUST_DRIVER_FAUX is not set
+# CONFIG_SAMPLE_RUST_DRIVER_AUXILIARY is not set
+# CONFIG_SAMPLE_RUST_SOC is not set
+# CONFIG_SAMPLE_RUST_HOSTPROGS is not set
+
+#
+# DAMON Samples
+#
+CONFIG_SAMPLE_DAMON_WSSE=y
+CONFIG_SAMPLE_DAMON_PRCL=y
+CONFIG_SAMPLE_DAMON_MTIER=y
+# end of DAMON Samples
+
 CONFIG_HAVE_SAMPLE_FTRACE_DIRECT=y
 CONFIG_HAVE_SAMPLE_FTRACE_DIRECT_MULTI=y
 CONFIG_ARCH_HAS_DEVMEM_IS_ALLOWED=y
@@ -12573,7 +12654,7 @@
 # x86 Debugging
 #
 CONFIG_EARLY_PRINTK_USB=y
-# CONFIG_X86_VERBOSE_BOOTUP is not set
+CONFIG_X86_VERBOSE_BOOTUP=y
 CONFIG_EARLY_PRINTK=y
 CONFIG_EARLY_PRINTK_DBGP=y
 CONFIG_EARLY_PRINTK_USB_XDBC=y
@@ -12656,9 +12737,9 @@
 #
 # Rust hacking
 #
-# CONFIG_RUST_DEBUG_ASSERTIONS is not set
+CONFIG_RUST_DEBUG_ASSERTIONS=y
 CONFIG_RUST_OVERFLOW_CHECKS=y
-# CONFIG_RUST_BUILD_ASSERT_ALLOW is not set
+CONFIG_RUST_BUILD_ASSERT_ALLOW=y
 # end of Rust hacking
 # end of Kernel hacking
 
